name: dr_map
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  json_serializable: ^6.9.2
  riverpod_annotation: ^2.6.1

  flutter_localizations: 
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  build_runner:
  custom_lint:
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/svgs/map_assets/
    - assets/svgs/provinces/
